import { applicationView, dateView, esc, resolveStatus } from './model.mjs';

function renderPhoto(slot,label,photos,{className='photo-frame',eager=false}={}) {
  const photo = photos.get(slot);
  if (!photo) return `<div class="${className}" role="img" aria-label="${esc(label)}"><span class="photo-placeholder-label">写真準備中</span></div>`;
  const src = photo.src || photo.variants?.fallback || photo.variants?.webp || photo.variants?.avif;
  const sources = `${photo.variants?.avif ? `<source type="image/avif" srcset="${esc(photo.variants.avif)}">` : ''}${photo.variants?.webp ? `<source type="image/webp" srcset="${esc(photo.variants.webp)}">` : ''}`;
  return `<figure class="${className}" style="--photo-focal:${esc(photo.focalMobile || '50% 50%')}"><picture>${sources}<img src="${esc(src)}" alt="${esc(photo.alt || '')}" width="${esc(photo.width || '')}" height="${esc(photo.height || '')}" loading="${eager ? 'eager' : 'lazy'}" decoding="async"${eager ? ' fetchpriority="high"' : ''}></picture>${photo.caption ? `<figcaption class="photo-caption">${esc(photo.caption)}</figcaption>` : ''}</figure>`;
}

export function renderHtml({eventsData,contentData,photosData,site,now=new Date()}) {
  const primary = eventsData.events.find(event => event.id === eventsData.primaryEventId);
  const future = eventsData.events.filter(event => event.id !== primary.id);
  const sections = new Map(contentData.sections.filter(section => section.enabled && (site.publishMode === 'preview' || section.approvalStatus === 'approved')).map(section => [section.sectionId,section]));
  const photos = new Map(photosData.photos.filter(photo => photo.slot && (site.publishMode === 'preview' ? photo.publicationStatus !== 'rejected' : photo.publicationStatus === 'approved')).map(photo => [photo.slot,photo]));
  const section = id => sections.get(id);
  const draft = id => site.publishMode === 'preview' && section(id)?.approvalStatus === 'draft' ? '<p class="verify-note">内容確認中のプレビューです</p>' : '';
  const date = dateView(primary);
  const app = applicationView(primary,resolveStatus(primary,now));
  const start = primary.startTime ? `${esc(primary.startTime)}〜` : '開始時間は後日公開';
  const venue = primary.venue || '会場は後日公開';
  const updated = new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',dateStyle:'long',timeStyle:'short'}).format(new Date(site.updatedAt));
  const noindex = site.publishMode === 'preview' ? '<meta name="robots" content="noindex,nofollow">' : '';

  return `<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#F6F5F1"><meta name="description" content="${esc(site.schoolName)} 2026年度学校説明会の案内。10月の学校説明会を中心に、開催情報と学校の雰囲気を紹介します。">${noindex}<meta property="og:title" content="${esc(site.schoolName)}｜学校説明会 2026"><meta property="og:description" content="目黒高校を、ひと足先に歩いてみよう。学校説明会の開催情報と来校前の学校体験。"><title>${esc(site.schoolName)}｜学校説明会 2026</title><link rel="stylesheet" href="css/style.css"><script src="js/app.js" defer></script></head>
<body><a class="skip-link" href="#main">本文へ移動</a><header class="site-header" id="top"><div class="header-inner"><a class="brand" href="#top"><small>2026 SCHOOL INFORMATION SESSION</small><strong>${esc(site.schoolName)}</strong></a><span class="header-status">${esc(app.label)}</span><nav class="header-nav" aria-label="主要メニュー"><a href="#discover">体験内容</a><a href="#information">開催情報</a><a href="#application">申込案内</a></nav></div></header>
<main id="main">
<section class="hero" id="entrance" aria-labelledby="hero-title"><div class="page-shell hero-topline"><p class="hero-event-kicker">2026年10月 学校説明会</p><span class="hero-status">${esc(app.label)}</span></div><div class="page-shell hero-grid"><div class="hero-info"><h1 class="hero-title" id="hero-title">${esc(section('entrance')?.heading || '目黒高校を、ひと足先に歩いてみよう。')}</h1><p class="hero-lead">${esc(section('entrance')?.body || '')}</p></div><div class="event-glass"><div class="event-date">${esc(date.short)}${date.weekday ? `<small>${esc(date.weekday)}</small>` : ''}</div><p class="event-details-mini"><strong>${esc(date.full)}</strong><br>${start}／${esc(venue)}</p><div class="cta-row"><a class="primary-cta" data-hero-cta href="${esc(app.href)}">${esc(app.cta)}</a><a class="secondary-link" href="#discover">説明会でできることを見る</a></div><p class="cta-helper">${esc(app.helper)}</p></div></div><div data-hero-media>${renderPhoto('hero','目黒高校の校内写真を掲載予定',photos,{className:'hero-media',eager:true})}</div></section>
${section('discover') ? `<section class="section" id="discover"><div class="page-shell"><p class="section-label">DISCOVER</p><h2 class="section-title">${esc(section('discover').heading)}</h2>${draft('discover')}<div class="discover-grid"><a class="discover-item" href="#explore"><span>01</span><strong>生徒と校内を歩く</strong><p>在校生の視点から、普段過ごす場所を知る。</p></a><a class="discover-item" href="#experience"><span>02</span><strong>学校の活気を感じる</strong><p>応援パフォーマンスの実施内容は確認後に公開。</p></a><a class="discover-item" href="#learning"><span>03</span><strong>学びと学校生活を知る</strong><p>学校説明で扱うテーマは確認済み情報だけを掲載。</p></a></div></div></section>` : ''}
${section('explore') ? `<section class="section section--canvas" id="explore"><div class="page-shell story-grid"><div><div data-explore-media>${renderPhoto('explore-main','生徒が来校者を案内する写真を掲載予定',photos,{className:'photo-frame photo-frame--portrait'})}</div><div class="caption-panel">生徒と歩く校内｜掲載写真・見学範囲は確認後に更新</div><div class="story-secondary">${renderPhoto('explore-secondary','学校の日常写真を掲載予定',photos,{className:'photo-frame photo-frame--wide'})}</div></div><div class="story-body"><p class="section-label">EXPLORE</p><h2 class="section-title">${esc(section('explore').heading)}</h2><p class="section-copy">${esc(section('explore').body)}</p>${draft('explore')}<a class="text-link" href="#information">開催情報を見る →</a></div></div></section>` : ''}
${section('students') ? `<section class="section" id="students"><div class="page-shell meet-grid"><div><p class="section-label">MEET</p><h2 class="section-title">${esc(section('students').heading)}</h2><p class="section-copy">${esc(section('students').body)}</p>${draft('students')}</div>${renderPhoto('students','目黒高校の生徒の日常写真を掲載予定',photos,{className:'photo-frame photo-frame--portrait'})}</div></section>` : ''}
${section('experience') ? `<section class="section section--canvas" id="experience"><div class="page-shell"><p class="section-label">EXPERIENCE</p><h2 class="section-title">${esc(section('experience').heading)}</h2>${draft('experience')}${renderPhoto('experience','応援パフォーマンス写真を掲載予定',photos,{className:'experience-photo'})}<div class="experience-copy"><p>${esc(section('experience').body)}</p><a class="text-link" href="#information">10月の開催情報へ →</a></div></div></section>` : ''}
${section('learning') ? `<section class="section" id="learning"><div class="page-shell learning-grid"><div><p class="section-label">LEARN</p><h2 class="section-title">${esc(section('learning').heading)}</h2><p class="section-copy">${esc(section('learning').body)}</p>${draft('learning')}</div><div class="topic-list">${['教育・学び','学校生活','進路','入試'].map(item => `<div class="topic"><strong>${item}</strong><span>確認後に公開</span></div>`).join('')}<a class="text-link" href="#information">日時・対象・申込方法を確認する →</a></div></div></section>` : ''}
<section class="section section--canvas information" id="information" data-hide-sticky-when-visible><div class="page-shell info-layout"><div><p class="section-label">INFORMATION</p><h2 class="section-title">${esc(section('information')?.heading || '10月 学校説明会')}</h2><div class="big-date">${esc(date.short)}<small>${esc(date.full)}</small></div><p class="info-status">${esc(app.label)}</p></div><div><dl class="info-list"><div><dt>開催日</dt><dd>${primary.date ? `<time datetime="${esc(primary.date)}">${esc(date.full)}</time>` : '詳細は後日公開'}</dd></div><div><dt>受付時間</dt><dd>${esc(primary.receptionTime || '後日公開')}</dd></div><div><dt>開始</dt><dd>${start}</dd></div><div><dt>会場</dt><dd>${esc(venue)}</dd></div><div><dt>対象</dt><dd>${esc(primary.audience || '後日公開')}</dd></div><div><dt>申込期間</dt><dd>${primary.application.opensAt || primary.application.closesAt ? '確認済み情報を掲載' : '後日公開'}</dd></div><div><dt>情報確認</dt><dd>${esc(updated)}</dd></div></dl><div class="application-box" id="application"><h3>申し込みについて</h3><p>${esc(app.label)}。${esc(app.helper)}</p><a class="primary-cta" href="${esc(app.href)}">${esc(app.cta)}</a></div></div></div></section>
<section class="section" id="upcoming"><div class="page-shell"><p class="section-label">UPCOMING EVENTS</p><h2 class="section-title">${esc(section('upcoming')?.heading || '11月・12月の開催予定')}</h2><div class="upcoming-list">${future.map(event => { const itemDate = dateView(event); return `<article class="upcoming-item"><div class="upcoming-month">${event.month}月</div><div><h3>${esc(event.title)}</h3><p>${esc(itemDate.full)}${event.startTime ? `／${esc(event.startTime)}〜` : ''}${event.venue ? `／${esc(event.venue)}` : ''}</p><p>申込詳細は後日公開</p></div></article>`; }).join('')}</div></div></section>
${section('visit') ? `<section class="section section--canvas" id="visit" data-hide-sticky-when-visible><div class="page-shell visit-grid">${renderPhoto('visit','来校を迎える学校入口写真を掲載予定',photos,{className:'visit-photo'})}<div class="visit-panel"><p class="section-label">VISIT</p><h2 class="section-title">${esc(section('visit').heading)}</h2><p class="section-copy">${esc(section('visit').body)}</p><div class="event-glass"><strong>${esc(date.full)}</strong><p class="event-details-mini">${start}／${esc(venue)}<br>${esc(app.label)}</p><a class="primary-cta" href="${esc(app.href)}">${esc(app.cta)}</a></div></div></div></section>` : ''}
</main><footer class="site-footer"><div class="page-shell footer-grid"><div><div class="footer-name">${esc(site.schoolName)}</div><div class="footer-meta">${esc(site.address)}<br>${esc(site.access)}<br>更新：${esc(updated)}</div></div><div class="footer-links"><a href="${esc(site.officialUrl)}">公式学校サイト</a><a href="${esc(site.meetingInfoUrl)}">学校説明会の公式案内</a><a href="${esc(site.contact.href)}">${esc(site.contact.label)} ${esc(site.contact.value)}</a><button class="motion-toggle" type="button" data-motion-toggle aria-pressed="false">動きを減らす</button></div></div></footer><div class="sticky-application" data-sticky-application hidden><a class="primary-cta" href="${esc(app.href)}">${esc(app.cta)}</a></div></body></html>`;
}
